### ISSUE TITLE
Code Review 6/27

### ISSUE THREAD

**Issue by ChibuezeEjiofor** [Nwanekwup/RhythME#1]
### Feedback

- Use a constant for these repeated strings. https://github.com/Nwanekwup/RhythME/blob/c414736837f60e358ff4e49d5bacc114cf9bb9f5/frontend/src/components/LoginSignup.jsx#L20C1-L21C1
- Otherwise looks good to me.
- Include more descriptive commit names. For example, "added new button", "fixed x bug".

**Comment by Nwanekwup** [comment]
Okay i'll do that. I'm not sure what you really mean by the constants

**Comment by ChibuezeEjiofor** [comment]
I was referring to the strings "Sign Up" and "Login" that are used in multiple places. This is a development anti-pattern called a magic string. Link for more context https://deviq.com/antipatterns/magic-strings.

**Comment by Nwanekwup** [comment]
Okay, thank you. i will look into it
